import ApiData from '@/components/shared/context/ApiData'
import Navbar from '@/components/views/Navbar'
import './globals.css'

export const metadata = {
  title: 'Cryptocurrency Prices',
  description: 'Generated by Abdul-Basit',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="scrollbar-thin scrollbar-thumb-slate-400 scrollbar-track-gray-200">
        <Navbar />
        <ApiData>
          {children}
        </ApiData>
      </body>
    </html>
  )
}
